// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package protos

import (
	apierrors "github.com/alkaid/goerrors/apierrors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = apierrors.SupportPackageIsVersion1

var errUnknown *apierrors.Error
var errForbiddenServerOfSession *apierrors.Error
var errSessionNotFound *apierrors.Error

func init() {
	errUnknown = apierrors.New(500, "protos.ErrUnknown", PitayaError_ErrUnknown.String(), "")
	apierrors.Register(errUnknown)
	errForbiddenServerOfSession = apierrors.New(403, "protos.ErrForbiddenServerOfSession", "forbidden this session request the server,because session unbound", "err_pitaya_forbidden_server_of_session")
	apierrors.Register(errForbiddenServerOfSession)
	errSessionNotFound = apierrors.New(400, "protos.ErrSessionNotFound", "session not found", "err_pitaya_session_not_found")
	apierrors.Register(errSessionNotFound)
}

func ErrUnknown() *apierrors.Error {
	return errUnknown
}

// ErrForbiddenServerOfSession  禁止该session请求此服务器(session未绑定)
func ErrForbiddenServerOfSession() *apierrors.Error {
	return errForbiddenServerOfSession
}

func ErrSessionNotFound() *apierrors.Error {
	return errSessionNotFound
}
