// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: pitaya-protos/response.proto

package protos

import (
	apierrors "github.com/alkaid/goerrors/apierrors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   []byte            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status *apierrors.Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pitaya_protos_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pitaya_protos_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pitaya_protos_response_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Response) GetStatus() *apierrors.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_pitaya_protos_response_proto protoreflect.FileDescriptor

var file_pitaya_protos_response_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x69, 0x74, 0x61, 0x79, 0x61, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x1b, 0x5a, 0x08,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0xaa, 0x02, 0x0e, 0x4e, 0x50, 0x69, 0x74, 0x61,
	0x79, 0x61, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pitaya_protos_response_proto_rawDescOnce sync.Once
	file_pitaya_protos_response_proto_rawDescData = file_pitaya_protos_response_proto_rawDesc
)

func file_pitaya_protos_response_proto_rawDescGZIP() []byte {
	file_pitaya_protos_response_proto_rawDescOnce.Do(func() {
		file_pitaya_protos_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_pitaya_protos_response_proto_rawDescData)
	})
	return file_pitaya_protos_response_proto_rawDescData
}

var file_pitaya_protos_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pitaya_protos_response_proto_goTypes = []interface{}{
	(*Response)(nil),         // 0: protos.Response
	(*apierrors.Status)(nil), // 1: errors.Status
}
var file_pitaya_protos_response_proto_depIdxs = []int32{
	1, // 0: protos.Response.status:type_name -> errors.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pitaya_protos_response_proto_init() }
func file_pitaya_protos_response_proto_init() {
	if File_pitaya_protos_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pitaya_protos_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pitaya_protos_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pitaya_protos_response_proto_goTypes,
		DependencyIndexes: file_pitaya_protos_response_proto_depIdxs,
		MessageInfos:      file_pitaya_protos_response_proto_msgTypes,
	}.Build()
	File_pitaya_protos_response_proto = out.File
	file_pitaya_protos_response_proto_rawDesc = nil
	file_pitaya_protos_response_proto_goTypes = nil
	file_pitaya_protos_response_proto_depIdxs = nil
}
